### PR TITLE
Use mix format and credo

### PR DESCRIPTION
**Pull request by VitorTrin**
mix format is the formatter that is suposed to be the default linter for elixir, and credo is a static code analysis tool.
The usage of these are recommended but are optional.

### CODE REVIEW

**Review by grempe — APPROVED** [review]
This is a good change. Thanks.  Is there an update that should be made to the README to add any formatting steps?

**Comment by VitorTrin** [comment]
Can I add this workflow to your github actions?

**Comment by grempe** [comment]
> Can I add this workflow to your github actions?

Sure. Much appreciated.

**Comment by VitorTrin** [comment]
> This is a good change. Thanks. Is there an update that should be made to the README to add any formatting steps?

If want to have a Contributing section, I recomend adding that you recomend running `mix format` and `mix credo --strict` before submitting a new PR

**Comment by grempe** [comment]
Thank you for the contribution. New section added.

https://github.com/grempe/ex_rated#contributing

**Pull request merged**
