### PR TITLE
Matrix tests for Elixir/OTP versions and small refactors.

### PR DESCRIPTION
**Pull request by jechol**
* Add matrix tests for Elixir/OTP versions for Elixir >= 1.6.
* Remove deprecated Supervisor.Spec.worker usage.
* Remove `init/1` from generated docs.

### CODE REVIEW

**Comment by jechol** [comment]
Matrix tests was already useful this PR itself.
Only 1 combination failed at https://github.com/grempe/ex_rated/actions/runs/317756047

**Review by grempe — APPROVED** [review]
LGTM

**Comment by grempe** [comment]
Thanks for the pull request!

**Comment by grempe** [comment]
Version 2.0.1 with this PR included has been published. Thank you.

**Pull request merged**
